<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20240401221622" tests="2" file="unittest/loader.py" time="0.002" timestamp="2024-04-01T22:16:22" failures="0" errors="2" skipped="0">
	<testcase classname="unittest.loader._FailedTest" name="test_function2_tests" time="0.001" timestamp="2024-04-01T22:16:22">
		<error type="ImportError" message="Failed to import test module: test_function2_tests
Traceback (most recent call last):
  File &quot;/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG2/src/unittest/python/test_function2_tests.py&quot;, line 5, in &lt;module&gt;
    from src.main.python.UC3MTravel.hotel_management_exception import HotelManagementException
ModuleNotFoundError: No module named 'src'
"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_function2_tests
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG2/src/unittest/python/test_function2_tests.py", line 5, in <module>
    from src.main.python.UC3MTravel.hotel_management_exception import HotelManagementException
ModuleNotFoundError: No module named 'src'

]]></error>
	</testcase>
	<testcase classname="unittest.loader._FailedTest" name="test_hotel_reservation_tests" time="0.000" timestamp="2024-04-01T22:16:22">
		<error type="ImportError" message="Failed to import test module: test_hotel_reservation_tests
Traceback (most recent call last):
  File &quot;/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG2/src/unittest/python/test_hotel_reservation_tests.py&quot;, line 5, in &lt;module&gt;
    from src.main.python.UC3MTravel.hotel_management_exception import HotelManagementException
ModuleNotFoundError: No module named 'src'
"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_hotel_reservation_tests
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG2/src/unittest/python/test_hotel_reservation_tests.py", line 5, in <module>
    from src.main.python.UC3MTravel.hotel_management_exception import HotelManagementException
ModuleNotFoundError: No module named 'src'

]]></error>
	</testcase>
</testsuite>
